# Generated by Django 3.2.6 on 2021-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePeerUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('item_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
